name: Server Maintenance
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prune:
    runs-on: ${{ vars.RUNNER }}
    timeout-minutes: 15
    steps:
      - run: |
          docker volume prune -f
          docker image prune -af --filter until=168h
          docker builder prune -f --filter until=168h

  ssl-renew:
    runs-on: ${{ vars.RUNNER }}
    environment: production
    timeout-minutes: 15
    steps:
      - uses: The-macharia/odoo-actions/ssl-renew@v1
        with:
          stack: ${{ vars.STACK }}
